# Prettier outputs
alias ls="ls -Aosh --color=auto"
alias dir="dir -A --color=auto"
alias lc="ls -ACF --color=auto"
alias grep="grep --color=auto"

# Functionality
alias mv="mv -i"
alias update="yay -Syu --ignore bitwig-studio"

# Shortcuts
alias edit="_open_files_for_editing"
alias q="exit"

# SSH
alias lensserver="ssh lena@lensserver"
alias arcade="ssh pi@retropie"
